import matplotlib as plt

from EqualFragments.EqualMinimalOrbitCascade import*
from PerfectMerging.MinimalOrbitCascade import*


def CollisionExample(): #Demonstration of the orbit collider generating orbits
    CollisionGraph(2*au,0.3,0,2.1*au,0.1,2,1.2e30,2e10,2e10)
    plt.show()
    return
def CollisionRadius():
    RadialGraph(2*au,0.99,2.1*au,0.993)
    return

#These Examples use figures from our problem, found from papers
def CollisionofAsteroids(): #Shows the first generation orbits generated by colliding asteroids
    CollisionGraph(2*au,0.99,0,2.1*au,0.993,2,1.2e30,2e10,2e10)
    plt.show()
    return




def MinimalAsteroidCascadeOrbits(N): #plots the orbits the lowest eccentricity in each generation generation orbits generated by colliding asteroids
    MinimalCircularisationPolarGraph(2*au,0.99,0,2.1*au,0.993,2,1.2e30,2e6,2e6,N)
    return
def MinimalAsteroidCascadeEccentricity(N): #plots the lowest eccentricity of each orbit against the generation number
    MinimalCircularisationEccentricityGraph(2*au,0.99,0,2.1*au,0.993,2,1.2e30,2e10,2e10,N)
    return

def MinimalAsteroidLambdaEccentricity(N,Ns):
    MinimalEccentricitySGraph(2*au,0.99,2.1*au,0.993,1.2e30,2e10,2e10,N,Ns)
    return

def EqualCollisionofAsteroids(): #Shows the first generation orbits generated by colliding asteroids
    EqualCollisionGraph(2*au,0.99,0,2.1*au,0.993,2,1.2e30)
    plt.show()
    return

def EqualCollisionExample(): #Demonstration of the orbit collider generating orbits
    EqualCollisionGraph(2*au,0.3,0,2.1*au,0.1,2,1.2e30)
    plt.show()
    return
def EqualMinimalAsteroidCascadeOrbits(N): #plots the orbits the lowest eccentricity in each generation generation orbits generated by colliding asteroids
    EqualMinimalCircularisationPolarGraph(2*au,0.99,0,2.1*au,0.993,2,1.2e30,N)
    return
def EqualMinimalAsteroidCascadeEccentricity(N): #plots the lowest eccentricity of each orbit against the generation number
    EqualMinimalCircularisationEccentricityGraph(2*au,0.99,0,2.1*au,0.993,2,1.2e30,N)
    return

def EqualMinimalAsteroidLambdaEccentricity(N,Ns):
    EqualMinimalEccentricitySGraph(2*au,0.99,2.1*au,0.993,1.2e30,N,Ns)
    return


#CollisionRadius() #Graph 1
#CollisionExample() #Graph 2
#MinimalAsteroidCascadeOrbits(10) #Graph 3
MinimalAsteroidLambdaEccentricity(15,10) #Graph 4


#MinimalAsteroidCascadeEccentricity(20) #Graph ?



#EQUAL REGIME GRAPHS
#EqualCollisionExample()
#EqualMinimalAsteroidCascadeOrbits(20)
#EqualMinimalAsteroidCascadeEccentricity(20)
#EqualMinimalAsteroidLambdaEccentricity(10,10)
#CollisionofAsteroids()
