import matplotlib as plt

from KCollisions.MinimalOrbitCascade import*
from Old.EqualFragments.EqualMinimalOrbitCascade import*


def CollisionExample(): #Demonstration of the orbit collider generating orbits
    CollisionGraph(2*au,0.3,0,2.1*au,0.1,2,1.2e30,2e10,2e10)
    plt.show()
    return

def CollisionEllipse(): #Demonstration of the orbit collider generating orbits
    CollisionGraph(2*au,0.1,0,2.1*au,0.6,2.7,1.2e30,2e10,2e10)
    plt.show()
    return

def CollisionRadius():
    RadialGraph(2*au,0.995,2.1*au,0.993)
    return

#These Examples use figures from our problem, found from papers
def CollisionofAsteroids(K): #Shows the first generation orbits generated by colliding asteroids
    CollisionGraph(2*au,0.995,0,2.1*au,0.993,2,1.2e30,2e10,2e10,K)
    plt.show()
    return

def MinimalAsteroidCascadeOrbits(x,K,N): #plots the orbits the lowest eccentricity in each generation generation orbits generated by colliding asteroids
    MinimalCircularisationPolarGraph(x,2*au,0.99,0,2.1*au,0.993,2,1.2e30,2e6,2e6,K,N)
    return
def MinimalAsteroidCascadeEccentricity(x,K,N): #plots the lowest eccentricity of each orbit against the generation number
    MinimalCircularisationEccentricityGraph(x,2*au,0.99,0,2.1*au,0.993,2,1.2e30,2e10,2e10,K,N)
    return

def MinimalAsteroidLambdaEccentricity(x,K,N,Ns):
    MinimalEccentricitySGraph(x,2*au,0.99,2.1*au,0.993,1.2e30,2e10,2e10,K,N,Ns)
    return

def EqualCollisionofAsteroids(): #Shows the first generation orbits generated by colliding asteroids
    EqualCollisionGraph(2*au,0.99,0,2.1*au,0.993,2,1.2e30)
    plt.show()
    return

def EqualCollisionExample(): #Demonstration of the orbit collider generating orbits
    EqualCollisionGraph(2*au,0.3,0,2.1*au,0.1,2,1.2e30)
    plt.show()
    return
def EqualMinimalAsteroidCascadeOrbits(N): #plots the orbits the lowest eccentricity in each generation generation orbits generated by colliding asteroids
    EqualMinimalCircularisationPolarGraph(2*au,0.99,0,2.1*au,0.993,2,1.2e30,N)
    return
def EqualMinimalAsteroidCascadeEccentricity(N): #plots the lowest eccentricity of each orbit against the generation number
    EqualMinimalCircularisationEccentricityGraph(2*au,0.99,0,2.1*au,0.993,2,1.2e30,N)
    return

def EqualMinimalAsteroidLambdaEccentricity(N,Ns):
    EqualMinimalEccentricitySGraph(2*au,0.99,2.1*au,0.993,1.2e30,N,Ns)
    return


#CollisionRadiu
# s() #Graph 1
#CollisionExample(1) #Graph 2
#MinimalAsteroidCascadeOrbits(1,10) #Graph 3
#MinimalAsteroidLambdaEccentricity('a',1,15,10) #Graph 4


#MinimalAsteroidCascadeEccentricity(1,20) #Graph ?



#EQUAL REGIME GRAPHS
#EqualCollisionExample()
#EqualMinimalAsteroidCascadeOrbits(20)
#EqualMinimalAsteroidCascadeEccentricity(20)
#EqualMinimalAsteroidLambdaEccentricity(10,10)
#CollisionofAsteroids(1)


#CollisionEllipse()
CollisionEllipse()
#CollisionofAsteroids(1)