from KCollisions.MinimalOrbitCascade import*
from KCollisions.OrbitCascade import*


def CollisionExample(): #Demonstration of the orbit collider generating orbits
    CollisionGraph(2*au,0.3,0,2.1*au,0.1,2,1.2e30,2e10,2e10)
    plt.show()
    return

#These Examples use figures from our problem, found from papers
def CollisionofAsteroids(): #Shows the first generation orbits generated by colliding asteroids
    CollisionGraph(2*au,0.99,0,2.1*au,0.993,2,1.2e30,2e10,2e10)
    return

def AsteroidCascadeOrbits(N): #plots the orbits the lowest eccentricity in each generation generation orbits generated by colliding asteroids
    CircularisationPolarGraph(2*au,0.99,0,2.1*au,0.993,2,1.2e30,2e10,2e10,N)
    return

def MinimalAsteroidCascadeOrbits(N): #plots the orbits the lowest eccentricity in each generation generation orbits generated by colliding asteroids
    MinimalCircularisationPolarGraph(2*au,0.99,0,2.1*au,0.993,2,1.2e30,2e10,2e10,N)
    return

def AsteroidCascadeEccentricity(N): #plots the lowest eccentricity of each orbit against the generation number
    CircularisationEccentricityGraph(2*au,0.99,0,2.1*au,0.993,2,1.2e30,2e10,2e10,N)
    return
def MinimalAsteroidCascadeEccentricity(N): #plots the lowest eccentricity of each orbit against the generation number
    MinimalCircularisationEccentricityGraph(2*au,0.99,0,2.1*au,0.993,2,1.2e30,2e10,2e10,N)
    return

def MinimalAsteroidLambdaEccentricity(N,Ns):
    MinimalEccentricitySGraph(2*au,0.99,2.1*au,0.993,1.2e30,2e10,2e10,N,Ns)

#MinimalAsteroidCascadeEccentricity(20)
MinimalAsteroidCascadeOrbits(20)
# Used for Graph
#MinimalAsteroidLambdaEccentricity(10,10) Used for Graph
